### ISSUE TITLE
AT: Write Tests for Session Authentication

### ISSUE THREAD

**Issue by dylanfernandes** [jacobrs/SOEN341#125]
## Task Description
Implement code to get a valid return value from the authenticateSession function in order to test the valid and invalid authentication cases.

## Task Breakdown
- [ ] obtain valid return from authenticateSession function
- [ ] test valid authentication case
- [ ] test invalid authentication case

## Agile Information
**Priority:** medium
**Risk:** Low
**Story Points:** 3

**Comment by dylanfernandes** [comment]
<img width="343" alt="screen shot 2017-04-11 at 10 15 29 pm" src="https://cloud.githubusercontent.com/assets/11564885/24938332/805933c8-1f04-11e7-9bb4-aca1887626f8.png">
@jacobrs this is not feasible according to @pbgnz

**Comment by dylanfernandes** [comment]
Closing this issue because our test suite doesn't allow persistent cookies to be tested.
