### ISSUE TITLE
USERSTORY: Add a user to a study group

### ISSUE THREAD

**Issue by Philippe229** [jacobrs/SOEN341#127]
## Task Description
As a user, I want to add other users to a study group I belong.

## Task Breakdown
- [x] Make a field to enter another user's email and a button to add the user
- [x] Make a listener which will search a user by email
- [x] Create an endpoint to search for a user by email
- [x] Use the back-end endpoint to add the user to the study group

## Agile Information
Priority: high  
Risk: low     
Story points: 3

**Comment by Philippe229** [comment]
Blocked by #79

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1035220095
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=694937366
Result of a sad path AT for this UserStory.
