### ISSUE TITLE
USERSTORY: Add Member

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#131]
## Task Description
As a user, after I create a study group for a class, I want to be able to add other users into that study group. 

## Task Breakdown
- [x] Have a UI component that allows users in a study group to add others
- [x] When a user adds an other one to the study group, it should appear in their list of SGs
- [x] Make sure that every study group has its own chat, and that messages are sent to the correct group

## Agile Info
Risk: medium
Priority: high
Story Points: 8

**Comment by MartinSpasov** [comment]
@jacobrs hit me up if you want me to do the frontend part of this!

**Comment by pbgnz** [comment]
What's your status on this task?

**Comment by jacobrs** [comment]
Still need to do the front end. Its on the back-burner since I have 2 exams this week.
