### ISSUE TITLE
USERSTORY: New UI Kit

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#133]
## Task Description
As a user, I want the website to look polished and unique. I want that pages to not look recycled.

## Task Breakdown
- [x] Decide on a new Bootstrap UI kit for the website 
- [x] Implement the new UI kit
- [x] Make sure that nothing is moved out of place and everything remains functional

## Agile Info
Risk: low
Priority: low
Story Points: 3
