### ISSUE TITLE
Create Homepage(Landing Page)

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#25]
## Task Description
As a user, when I access the teamstudy webpage, I should be redirected to the home page/landing page of the website. I can also redirect to the login page and to the register page by clicking their according buttons. Finally, I can also read a description of what team study is about.

## Task Breakdown
- [ ] Create the home page design
- [ ]  Add the login and register buttons
- [ ] Add a description of the website

## Agile Information
Risk: Low
Story Points: 3

**Comment by pbgnz** [comment]
I thought we were doing this issue this sprint (3).

I think it is crucial to have a landing page with the description of the app. As for the design, let's keep it neat and simple.
