### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#40]
## Task Description
As a user I want to have a navigation bar that always stays on top of the website. It should allow me to access the important pages of the website.
## Task Breakdown
- [ ] Create a Navigation bar following the design at #39 
- [ ] The Navigation bar should always stay on the top on every webpage at the exception of the register page
- [ ] Every button should redirect the user to the corresponding page.
## Agile Information
Priority: medium
Risk: low 
Story points: 5
