### ISSUE TITLE
USERSTORY: Form Validation for Profile edit

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#44]
## Task Description
As a user , when I  edit my account information, I want to know that all the information I entered is valid. If something is not correct during that process I want to receive a notification clearly indicating what is wrong. I also want my password to have a security standard if I decide to edit it.

## Task Breakdown
- [x] Validate the information when editing an account (same as #48)
-  Password fits a certain standard (ex: 1 letter, 1 number, minimum 8 characters)
- Email is valid (something@something.something)
- Student id contains only numbers
- [x]  If any of above points are not correct, a message should indicate the user what is not correct
- [ ]  If edit is successful a message should indicate so
- [ ]  The user does not need to fill in all the areas. He might want to only change his password or name. etc.

## Agile Information
Priority: low
Risk: low
Story points: 3

**Comment by jacobrs** [comment]
BLOCKED by #42

**Comment by pbgnz** [comment]
Is this getting closed when #42  get merged?

**Comment by MartinSpasov** [comment]
After discussion, we decided that instead of allowing the user to only fill in certain parts of the form, we automatically fill the form with the information. The User just has the change what he need

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=954635512
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=637285571
Result of a sad path AT for this UserStory.
