### ISSUE TITLE
Registration Validation

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#48]
## Task Description
As a user , when I  create a new account, I want to have a confirmation that the account is successfully created. If something is not correct during that process I want to receive a notification clearly indicating what is wrong. I also want my password to have a security standard.

## Task Breakdown
- [x] Validation of registration for a new account
- -  Password fits a certain standard (ex: 1 letter, 1 number, minimum 8 characters)
- - Email is valid (something@something.something)
- - Student id contains only numbers
- [x]  If any of above points are not correct, a message should indicate the user what is missing
- [x]  If creation is successful a message should indicate so

## Agile Information
Risk: low
Story points: 3

**Comment by ONourry** [comment]
The styling could be improved as a future task but the functionalities are all working. Issue can be closed.
