### ISSUE TITLE
TESTING: Test API endpoints

### ISSUE THREAD

**Issue by pbgnz** [jacobrs/SOEN341#66]
## Task Description
The User API endpoints have been created and merged in issues #20 and #54. However, there are no unit tests done on the back-end.

## Task Breakdown
This issue is divided in two parts:

- [x] Setup mocha and chai for the back-end testing

- [x] Test the User API endpoint

- [x] Test the User authenticate `/me` endpoint

- [x] Test the User logout `/logout` endpoint

- [x] Test the StudyGroup API endpoint

- [x] Test the Chat Api and related enpoints

## Agile Information
**Risk**: low
**Estimated time:** 3hrs

**Comment by pbgnz** [comment]
After trying to setup mocha and chai for two days, I concluded that it would be easier to use the already installed testing module AVA.  The two main reasons are that:

1- It would be more time efficient since AVA is already set-up and [there are examples on MERN](https://github.com/Hashnode/mern-starter/blob/master/server/models/__tests__/post.spec.js)

2- It would be less heavy on the server

**Comment by jacobrs** [comment]
Also test `/me` and `/logout` endpoints

**Comment by pbgnz** [comment]
*Not* goal of the current sprint.

**Comment by jacobrs** [comment]
@pbgnz why is this no longer a goal? We require tests in order to close user stories.

**Comment by pbgnz** [comment]
@jacobrs the back-end is being tested using other tools at the moment. I wanted to prioritize the chat for this spring. So, me and Phil decided to meet this Friday after the tutorial and finish all the back-end tasks. 
 
So if everything goes according to plan, I will be working on finishing the tests by next week or so. Before the list increases lol.

**Comment by pbgnz** [comment]
This will be done this sprint. Phil can write the tests for his endpoints in this issue.

**Comment by pbgnz** [comment]
Cannot "mock" login for testing. Therefore, cannot test the *authenticated* endpoints.
