### ISSUE TITLE
USERSTORY: Chat Frontend

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#76]
The user wants a page for each study group he is a part of to chat with other members of the study group. An array will be fetched from the backend API and used to populate the chat component.
## Task Description
As an user I want to have acces to a chat group for every study group that I am part of.
## Task Breakdown
- [x] Design a chat interface and position it in somewhere easy to acces in the dashboard
- [x] Populate the chat with an array fetched from the backend API
- [x] Have a different chat available for every study group
## Agile Information
Priority: medium
Risk: medium
Story points: 5

**Comment by jacobrs** [comment]
BLOCKED by #78

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1440114081
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1341847408
Result of a sad path AT for this UserStory.

**Comment by MartinSpasov** [comment]
@simon-bourque Can this story be closed?

**Comment by simon-bourque** [comment]
Color of chat messages still needs to be worked on.  Will finish this as soon as #131 is done.

**Comment by simon-bourque** [comment]
still need filtering
