### ISSUE TITLE
USERSTORY: Chat Backend API

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#78]
## Task Description
Create an API to save messages, get messages, etc. Back-end for issue #76.

## Task Breakdown
- [x] Create a new model chat messages and update existing models
- [x] Create the GET, POST, DELETE endpoints for the chat messages
- [x] Create the controller and routes for the chat messages
- [x] Implement basic socket.io functionality
- [x] Link API with socket.io

## Agile Information
**Priority:** High
**Risk:** Low
**Story Points:** 5

**Comment by MartinSpasov** [comment]
(Burndown info) 4/5
