### ISSUE TITLE
USERSTORY: Study Group Component

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#79]
## Task Description
As a user, I would need to be able to see all the study groups I am currently enrolled into. They need to be visually appealing and simple to understand.

## Task Breakdown
- [x] Design a neat study group component, updating the initial design as needed.
- [x] Implement the new design into the dashboard
- [x] Using the backend API update the information in the new component with the study groups the user is enrolled into

## Agile Information
Priority: medium
Risk: low
Story points: 5

**Comment by jacobrs** [comment]
BLOCKED by #80

**Comment by MartinSpasov** [comment]
(Burndown info) 4/5

**Comment by ONourry** [comment]
Can this issue be closed?

**Comment by MartinSpasov** [comment]
is "Using the backend API update the information in the new component with the study groups the user is enrolled into" implemented?

**Comment by samantha-kerr** [comment]
No it's not, this is what I need help with

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=195117885
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1850721897
Result of a sad path AT for this UserStory.
