### ISSUE TITLE
USERSTORY: Study Group API

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#80]
## Task Description
As a user , I want to have the ability to create, join and delete study groups. 

## Task Breakdown
- [x] Created a new model for study groups
- [x] Created the GET, POST, DELETE endpoints for the study groups
- [x] Created the controller and routes for the study groups
## Agile Information
Priority: High  
Risk: med    
Story points: 5

**Comment by jacobrs** [comment]
Think this is done @pbgnz you should close it and unblock all the other dependant issues.
