### ISSUE TITLE
USERSTORY: When the user navigates the webpage he must still be logged

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#88]
## Task Description
As a user , when I navigate through the website, I want my account to stay logged in. Currently if I refresh the page or go to a different page, I need to log in again when I come back.

## Task Breakdown
- [x] When on website page, check cookies if user has already been authenticated
- [x] If user is already authenticated previously, retrieve that data and log in the user directly
- [x] If the user is authenticated when landing on `/` he/she should be redirected to `/profile`

## Agile Information
Priority: high
Risk: low
Story points: 3

**Comment by jacobrs** [comment]
@simon-bourque can I assign this to myself to finish the routing on the login?

**Comment by simon-bourque** [comment]
sounds good!
