### ISSUE TITLE
USERSTORY: Form for creating study groups

### ISSUE THREAD

**Issue by pbgnz** [jacobrs/SOEN341#97]
## Task Description
As a user, I am able to create a study group and join it by filling a form.

## Task Breakdown
- [ ] Make a form for creating study groups
- [ ] Use the post method of the `api/studyGroups` to send the form to the backend
- [ ] Validate the form on the front-end
- [ ] Add button in the dashboard to either redirect to the form page or to pop a modal
## Agile Information
Priority: high  
Risk: low     
Story points: 3

**Comment by pbgnz** [comment]
blocked by #80 . PR under code review in #95 .

**Comment by simon-bourque** [comment]
This is also blocked by #79, we need an actual study group component in front end first

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1983910256
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=909817991
Result of a sad path AT for this UserStory.
